// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: ranks.sql

package db

import (
	"context"
)

const getRanks = `-- name: GetRanks :many
SELECT id, name FROM rank
`

func (q *Queries) GetRanks(ctx context.Context) ([]Rank, error) {
	rows, err := q.db.Query(ctx, getRanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rank
	for rows.Next() {
		var i Rank
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
